import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'node20',
  splitting: false,
  minify: false,
  // src/version.ts is generated by prebuild — excluded from source control
  // but must exist before tsup runs (enforced by package.json prebuild hook)
});
