// Generates src/version.ts from package.json at prebuild time.
// Single source of truth for the SDK version string — prevents the Fyber-era
// problem of version drift between package.json and a hard-coded User-Agent.
// See SDK_PLAN.md §2.1.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(__dirname, '..', 'package.json');
const outPath = join(__dirname, '..', 'src', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

const content = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Pinned to package.json version at prebuild time.
export const SDK_VERSION = ${JSON.stringify(pkg.version)};
export const SDK_NAME = ${JSON.stringify(pkg.name)};
`;

writeFileSync(outPath, content);
console.log(`Generated ${outPath} (version ${pkg.version})`);
